### ISSUE TITLE
Dockerize development environment

### ISSUE THREAD

**Issue by neelkamath** [neelkamath/crystal-skull#18]
Currently only the production environment has been containerized (i.e., `Dockerfile`). The development environment should be containerized as well (i.e., `dev.Dockerfile`).

The development Dockerfile will look similar to the existing [Dockerfile](https://github.com/neelkamath/crystal-skull/blob/master/Dockerfile). All the relevant commands for running the server are documented in [docs/development.md](https://github.com/neelkamath/crystal-skull/blob/master/docs/developing.md). 

Containerizing the development environment will bring the benefits of reducing the gap between development and production environments, make setting up the project easier because there’s nothing to install (except Docker), and make it easier to expand infrastructure for adding other servers and databases.

**Comment by AlexGustafsson** [comment]
I can take a look at it.

**Comment by neelkamath** [comment]
@AlexGustafsson go ahead! Let me know if I can assign the issue to you.

**Comment by AlexGustafsson** [comment]
@neelkamath Yes, please assign me.

What development flow are you considering for the docker image? The usual thing I guess is to run "docker build" to build the project and then "docker run" to run it. Another option is to drop the docker container into a shell where the user would interact with gradlew as if they had it installed on their own system. It could allow for some faster iterations when building and testing the server. One could even go as far as to mount the source directory as a volume to be able to start the docker container once and then just change to code in ones editor and run gradle commands in the container.

What flow would you like?

**Comment by neelkamath** [comment]
My evaluation of the options are:
- `docker build`: Hot reload will be useless since the new files will have to be manually built with this command each time
- using the container as a shell: decent, but has the problem of the user initially changing directories manually in the shell on initial startup, not a big problem though
- mounting: seems to be optimal, unless you think the shell option is better due to the possibly increased isolation

In either case, you'll have to remember to update the `.dockerignore`

**Comment by AlexGustafsson** [comment]
@neelkamath I think the approach I've implemented allows for all three approaches. I've opened up a pull request which adds a Dockerfile for development. Nothing else is changed, so I've not updated the `.dockerignore` file.

**Comment by neelkamath** [comment]
My bad; yea, with one of the approaches you needn't update the `.dockerignore`. Sorry, but I'll be replying a little late cuz I'm currently at a hackathon.
